name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: rustup toolchain install nightly --profile minimal && rustup default nightly
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --verbose
    - run: cargo test --verbose
    - run: cargo test --verbose --no-default-features
    - run: cargo test --verbose --all-features
    - run: cargo test --verbose -F fs
    - run: cargo test --verbose -F json
    - run: cargo test --verbose -F ratelimiter
    - run: cargo test --verbose -F airtable
    
